from __future__ import annotations

from portakal_app.models import CategoryDefinition, PortDefinition, WidgetDefinition
from portakal_app.ui import i18n
from portakal_app.ui.screens.color_screen import ColorScreen
from portakal_app.ui.screens.column_statistics_screen import ColumnStatisticsScreen
from portakal_app.ui.screens.csv_import_screen import CSVImportScreen
from portakal_app.ui.screens.data_info_screen import DataInfoScreen
from portakal_app.ui.screens.data_table_screen import DataTableScreen
from portakal_app.ui.screens.datasets_screen import DatasetsScreen
from portakal_app.ui.screens.edit_domain_screen import EditDomainScreen
from portakal_app.ui.screens.file_screen import FileScreen
from portakal_app.ui.screens.paint_data_screen import PaintDataScreen
from portakal_app.ui.screens.placeholder_screen import PlaceholderScreen
from portakal_app.ui.screens.rank_screen import RankScreen
from portakal_app.ui.screens.save_data_screen import SaveDataScreen

from portakal_app.ui.screens.aggregate_columns_screen import AggregateColumnsScreen
from portakal_app.ui.screens.apply_domain_screen import ApplyDomainScreen
from portakal_app.ui.screens.ca_screen import CAScreen
from portakal_app.ui.screens.continuize_screen import ContinuizeScreen
from portakal_app.ui.screens.correlations_screen import CorrelationsScreen
from portakal_app.ui.screens.data_sampler_screen import DataSamplerScreen
from portakal_app.ui.screens.dbscan_screen import DBSCANScreen
from portakal_app.ui.screens.discretize_screen import DiscretizeScreen
from portakal_app.ui.screens.distance_file_screen import DistanceFileScreen
from portakal_app.ui.screens.distance_map_screen import DistanceMapScreen
from portakal_app.ui.screens.distance_matrix_screen import DistanceMatrixScreen
from portakal_app.ui.screens.distance_transformation_screen import DistanceTransformationScreen
from portakal_app.ui.screens.distances_screen import DistancesScreen
from portakal_app.ui.screens.melt_screen import MeltScreen
from portakal_app.ui.screens.mds_screen import MDSScreen
from portakal_app.ui.screens.outliers_screen import OutliersScreen
from portakal_app.ui.screens.purge_domain_screen import PurgeDomainScreen
from portakal_app.ui.screens.randomize_screen import RandomizeScreen
from portakal_app.ui.screens.save_distance_matrix_screen import SaveDistanceMatrixScreen
from portakal_app.ui.screens.select_by_index_screen import SelectByIndexScreen
from portakal_app.ui.screens.split_screen import SplitScreen
from portakal_app.ui.screens.transpose_screen import TransposeScreen
from portakal_app.ui.screens.unique_screen import UniqueScreen

from portakal_app.ui.screens.concatenate_screen import ConcatenateScreen
from portakal_app.ui.screens.formula_screen import FormulaScreen
from portakal_app.ui.screens.create_class_screen import CreateClassScreen
from portakal_app.ui.screens.create_instance_screen import CreateInstanceScreen
from portakal_app.ui.screens.group_by_screen import GroupByScreen
from portakal_app.ui.screens.impute_screen import ImputeScreen
from portakal_app.ui.screens.merge_data_screen import MergeDataScreen
from portakal_app.ui.screens.pivot_table_screen import PivotTableScreen
from portakal_app.ui.screens.preprocess_screen import PreprocessScreen
from portakal_app.ui.screens.python_script_screen import PythonScriptScreen
from portakal_app.ui.screens.select_columns_screen import SelectColumnsScreen
from portakal_app.ui.screens.select_rows_screen import SelectRowsScreen

from portakal_app.ui.screens.bar_plot_screen import BarPlotScreen
from portakal_app.ui.screens.box_plot_screen import BoxPlotScreen
from portakal_app.ui.screens.distributions_screen import DistributionsScreen
from portakal_app.ui.screens.sieve_diagram_screen import SieveDiagramScreen
from portakal_app.ui.screens.mosaic_display_screen import MosaicDisplayScreen
from portakal_app.ui.screens.freeviz_screen import FreeVizScreen
from portakal_app.ui.screens.linear_projection_screen import LinearProjectionScreen
from portakal_app.ui.screens.radviz_screen import RadvizScreen
from portakal_app.ui.screens.heat_map_screen import HeatMapScreen
from portakal_app.ui.screens.line_plot_screen import LinePlotScreen
from portakal_app.ui.screens.scatter_plot_screen import ScatterPlotScreen
from portakal_app.ui.screens.tree_viewer_screen import TreeViewerScreen
from portakal_app.ui.screens.violin_plot_screen import ViolinPlotScreen
from portakal_app.ui.screens.venn_diagram_screen import VennDiagramScreen
from portakal_app.ui.screens.silhouette_plot_screen import SilhouettePlotScreen
from portakal_app.ui.screens.pythagorean_forest_screen import PythagoreanForestScreen
from portakal_app.ui.screens.pythagorean_tree_screen import PythagoreanTreeScreen
from portakal_app.ui.screens.cn2_rule_viewer_screen import CN2RuleViewerScreen
from portakal_app.ui.screens.nomogram_screen import NomogramScreen
from portakal_app.ui.screens.scoring_sheet_viewer_screen import ScoringSheetViewerScreen

from portakal_app.ui.screens.constant_screen import ConstantScreen
from portakal_app.ui.screens.naive_bayes_screen import NaiveBayesScreen
from portakal_app.ui.screens.knn_screen import KNNScreen
from portakal_app.ui.screens.tree_screen import TreeScreen
from portakal_app.ui.screens.random_forest_screen import RandomForestScreen
from portakal_app.ui.screens.logistic_regression_screen import LogisticRegressionScreen
from portakal_app.ui.screens.linear_regression_screen import LinearRegressionScreen
from portakal_app.ui.screens.svm_screen import SVMScreen
from portakal_app.ui.screens.neural_network_screen import NeuralNetworkScreen
from portakal_app.ui.screens.adaboost_screen import AdaBoostScreen
from portakal_app.ui.screens.gradient_boosting_screen import GradientBoostingScreen
from portakal_app.ui.screens.sgd_screen import SGDScreen
from portakal_app.ui.screens.pls_screen import PLSScreen
from portakal_app.ui.screens.curve_fit_screen import CurveFitScreen
from portakal_app.ui.screens.scoring_sheet_screen import ScoringSheetScreen
from portakal_app.ui.screens.cn2_rule_induction_screen import CN2RuleInductionScreen
from portakal_app.ui.screens.calibrated_learner_screen import CalibratedLearnerScreen
from portakal_app.ui.screens.stacking_screen import StackingScreen
from portakal_app.ui.screens.save_model_screen import SaveModelScreen
from portakal_app.ui.screens.load_model_screen import LoadModelScreen
from portakal_app.ui.screens.confusion_matrix_screen import ConfusionMatrixScreen
from portakal_app.ui.screens.test_and_score_screen import TestAndScoreScreen
from portakal_app.widgets.unsupervised.ow_hierarchical_clustering import OWHierarchicalClustering
from portakal_app.widgets.unsupervised.ow_kmeans import OWKMeans
from portakal_app.widgets.unsupervised.ow_pca import OWPCA
from portakal_app.ui.screens.tsne_screen import TSNEScreen
from portakal_app.ui.screens.manifold_learning_screen import ManifoldLearningScreen
from portakal_app.ui.screens.som_screen import SOMScreen
from portakal_app.ui.screens.louvain_clustering_screen import LouvainClusteringScreen


def _placeholder_factory(title: str, description: str):
    def factory() -> PlaceholderScreen:
        return PlaceholderScreen(title=i18n.t(title), message=i18n.t(description))

    return factory


def _inputs(*labels: str) -> tuple[PortDefinition, ...]:
    return tuple(PortDefinition(id=f"in-{index}", label=label) for index, label in enumerate(labels, start=1))


def _outputs(*labels: str) -> tuple[PortDefinition, ...]:
    return tuple(PortDefinition(id=f"out-{index}", label=label) for index, label in enumerate(labels, start=1))


def build_categories() -> list[CategoryDefinition]:
    return [
        CategoryDefinition(id="data", label=i18n.t("Data")),
        CategoryDefinition(id="transform", label=i18n.t("Transform")),
        CategoryDefinition(id="visualize", label=i18n.t("Visualize")),
        CategoryDefinition(id="model", label=i18n.t("Model")),
        CategoryDefinition(id="evaluate", label=i18n.t("Evaluate")),
        CategoryDefinition(id="unsupervised", label=i18n.t("Unsupervised")),
    ]


def build_widgets() -> list[WidgetDefinition]:
    return [
        WidgetDefinition(
            "file",
            "data",
            i18n.t("File"),
            True,
            FileScreen,
            i18n.t("Load a file dataset."),
            "file",
            (),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "csv-import",
            "data",
            i18n.t("CSV File Import"),
            True,
            CSVImportScreen,
            i18n.t("Preset-based import flow."),
            "csv",
            (),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "datasets",
            "data",
            i18n.t("Datasets"),
            True,
            DatasetsScreen,
            i18n.t("Explore packaged datasets."),
            "dataset",
            (),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "data-table",
            "data",
            i18n.t("Data Table"),
            True,
            DataTableScreen,
            i18n.t("Inspect loaded rows."),
            "table",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "paint-data",
            "data",
            i18n.t("Paint Data"),
            True,
            PaintDataScreen,
            i18n.t("Edit data manually."),
            "paint",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "data-info",
            "data",
            i18n.t("Data Info"),
            True,
            DataInfoScreen,
            i18n.t("Profile the dataset."),
            "info",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "rank",
            "data",
            i18n.t("Rank"),
            True,
            RankScreen,
            i18n.t("Rank features."),
            "rank",
            _inputs("Data"),
            _outputs("Scores"),
        ),
        WidgetDefinition(
            "edit-domain",
            "data",
            i18n.t("Edit Domain"),
            True,
            EditDomainScreen,
            i18n.t("Manage column roles."),
            "edit",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "color",
            "data",
            i18n.t("Color"),
            True,
            ColorScreen,
            i18n.t("Assign color metadata."),
            "color",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "column-statistics",
            "data",
            i18n.t("Column Statistics"),
            True,
            ColumnStatisticsScreen,
            i18n.t("Deep dive into column distributions."),
            "stats",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "save-data",
            "data",
            i18n.t("Save Data"),
            True,
            SaveDataScreen,
            i18n.t("Export the current dataset."),
            "save",
            _inputs("Data"),
            (),
        ),
        # --- Transform: Active widgets ---
        WidgetDefinition(
            "select-by-index",
            "transform",
            i18n.t("Select by Data Index"),
            True,
            SelectByIndexScreen,
            i18n.t("Match rows by index subset."),
            "index",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Matching Data", "Non-matching Data"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "randomize",
            "transform",
            i18n.t("Randomize"),
            True,
            RandomizeScreen,
            i18n.t("Shuffle rows or columns."),
            "randomize",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "purge-domain",
            "transform",
            i18n.t("Purge Domain"),
            True,
            PurgeDomainScreen,
            i18n.t("Remove unused values and constant features."),
            "purge",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "unique",
            "transform",
            i18n.t("Unique"),
            True,
            UniqueScreen,
            i18n.t("Filter duplicate rows."),
            "unique",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "apply-domain",
            "transform",
            i18n.t("Apply Domain"),
            True,
            ApplyDomainScreen,
            i18n.t("Apply template domain structure."),
            "domain",
            _inputs("Data"),
            _outputs("Data"),
            input_channels=("Data", "Template Data"),
        ),
        # --- Transform: Placeholder widgets (to be implemented) ---
        WidgetDefinition(
            "data-sampler",
            "transform",
            i18n.t("Data Sampler"),
            True,
            DataSamplerScreen,
            i18n.t("Sample a subset of the data."),
            "sampler",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Data Sample", "Remaining Data"),
        ),
        WidgetDefinition(
            "select-columns",
            "transform",
            i18n.t("Select Columns"),
            True,
            SelectColumnsScreen,
            i18n.t("Choose feature sets."),
            "columns",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "select-rows",
            "transform",
            i18n.t("Select Rows"),
            True,
            SelectRowsScreen,
            i18n.t("Filter rows by conditions."),
            "rows",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Matching Data", "Unmatched Data"),
        ),
        WidgetDefinition(
            "transpose",
            "transform",
            i18n.t("Transpose"),
            True,
            TransposeScreen,
            i18n.t("Flip rows and columns."),
            "transpose",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "split",
            "transform",
            i18n.t("Split"),
            True,
            SplitScreen,
            i18n.t("Split string column into indicators."),
            "split",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "merge-data",
            "transform",
            i18n.t("Merge Data"),
            True,
            MergeDataScreen,
            i18n.t("Join two datasets by column values."),
            "merge",
            _inputs("Data", "Extra Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "concatenate",
            "transform",
            i18n.t("Concatenate"),
            True,
            ConcatenateScreen,
            i18n.t("Append datasets vertically."),
            "concatenate",
            _inputs("Data"),
            _outputs("Data"),
            input_channels=("Primary Data", "Additional Data"),
            multi_input_channels=("Additional Data",),
        ),
        WidgetDefinition(
            "aggregate-columns",
            "transform",
            i18n.t("Aggregate Columns"),
            True,
            AggregateColumnsScreen,
            i18n.t("Compute row-wise aggregations."),
            "aggregate",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "group-by",
            "transform",
            i18n.t("Group By"),
            True,
            GroupByScreen,
            i18n.t("Group and aggregate data."),
            "groupby",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "pivot-table",
            "transform",
            i18n.t("Pivot Table"),
            True,
            PivotTableScreen,
            i18n.t("Create cross-tabulations."),
            "pivot",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "preprocess",
            "transform",
            "Preprocess",
            True,
            PreprocessScreen,
            i18n.t("Build preprocessing pipelines."),
            "preprocess",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "impute",
            "transform",
            i18n.t("Impute"),
            True,
            ImputeScreen,
            i18n.t("Fill missing values."),
            "impute",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "continuize",
            "transform",
            i18n.t("Continuize"),
            True,
            ContinuizeScreen,
            i18n.t("Convert categorical to numeric."),
            "continuize",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "discretize",
            "transform",
            i18n.t("Discretize"),
            True,
            DiscretizeScreen,
            i18n.t("Convert numeric to categorical."),
            "discretize",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "melt",
            "transform",
            i18n.t("Melt"),
            True,
            MeltScreen,
            i18n.t("Wide to long format."),
            "melt",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "create-class",
            "transform",
            i18n.t("Create Class"),
            True,
            CreateClassScreen,
            i18n.t("Create class from string patterns."),
            "createclass",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "create-instance",
            "transform",
            i18n.t("Create Instance"),
            True,
            CreateInstanceScreen,
            i18n.t("Create a single data instance."),
            "createinstance",
            _inputs("Data"),
            _outputs("Data"),
            input_channels=("Data", "Reference"),
        ),
        WidgetDefinition(
            "formula",
            "transform",
            i18n.t("Formula"),
            True,
            FormulaScreen,
            i18n.t("Construct features with expressions."),
            "formula",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "python-script",
            "transform",
            i18n.t("Python Script"),
            True,
            PythonScriptScreen,
            i18n.t("Run custom Python code."),
            "python",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "tree-viewer",
            "visualize",
            i18n.t("Tree Viewer"),
            True,
            TreeViewerScreen,
            i18n.t("Inspect trained tree structures and node selections."),
            "model",
            _inputs("Tree"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "box-plot",
            "visualize",
            i18n.t("Box Plot"),
            True,
            BoxPlotScreen,
            i18n.t("Visualize numeric quartiles or discrete value frequencies."),
            "stats",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "violin-plot",
            "visualize",
            i18n.t("Violin Plot"),
            True,
            ViolinPlotScreen,
            i18n.t("Show smoothed numeric distributions with selectable ranges."),
            "stats",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "distributions",
            "visualize",
            i18n.t("Distributions"),
            True,
            DistributionsScreen,
            i18n.t("Explore histograms and categorical distributions."),
            "barplot",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "scatter-plot",
            "visualize",
            i18n.t("Scatter Plot"),
            True,
            ScatterPlotScreen,
            i18n.t("Explore points visually."),
            "scatter",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data", "Features"),
            input_channels=("Data", "Data Subset", "Features"),
        ),
        WidgetDefinition(
            "line-plot",
            "visualize",
            i18n.t("Line Plot"),
            True,
            LinePlotScreen,
            i18n.t("Compare instance profiles across numeric features."),
            "linearprojection",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "bar-plot",
            "visualize",
            i18n.t("Bar Plot"),
            True,
            BarPlotScreen,
            i18n.t("Frequency bars for categorical or binned numeric columns."),
            "barplot",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "sieve-diagram",
            "visualize",
            i18n.t("Sieve Diagram"),
            True,
            SieveDiagramScreen,
            i18n.t("Association between two categorical variables."),
            "sieve",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data", "Features"),
        ),
        WidgetDefinition(
            "mosaic-display",
            "visualize",
            i18n.t("Mosaic Display"),
            True,
            MosaicDisplayScreen,
            i18n.t("Proportional mosaic plot for two categorical variables."),
            "mosaic",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "freeviz",
            "visualize",
            i18n.t("FreeViz"),
            True,
            FreeVizScreen,
            i18n.t("Force-directed linear projection onto 2D."),
            "freeviz",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data", "Components"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "linear-projection",
            "visualize",
            i18n.t("Linear Projection"),
            True,
            LinearProjectionScreen,
            i18n.t("Scatter plot of two user-selected numeric axes."),
            "linearprojection",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data", "Components"),
            input_channels=("Data", "Data Subset", "Projection"),
        ),
        WidgetDefinition(
            "radviz",
            "visualize",
            i18n.t("Radviz"),
            True,
            RadvizScreen,
            i18n.t("Radial visualization with feature anchors on a circle."),
            "radviz",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "heat-map",
            "visualize",
            i18n.t("Heat Map"),
            True,
            HeatMapScreen,
            i18n.t("Pearson correlation matrix for numeric columns."),
            "heatmap",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "venn-diagram",
            "visualize",
            i18n.t("Venn Diagram"),
            True,
            VennDiagramScreen,
            i18n.t("Overlap of rows or features across multiple datasets."),
            "venn",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data 1", "Data 2", "Data 3", "Data 4", "Data 5"),
        ),
        WidgetDefinition(
            "silhouette-plot",
            "visualize",
            i18n.t("Silhouette Plot"),
            True,
            SilhouettePlotScreen,
            i18n.t("Assess cluster quality with silhouette scores."),
            "silhouette",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "pythagorean-forest",
            "visualize",
            i18n.t("Pythagorean Forest"),
            True,
            PythagoreanForestScreen,
            i18n.t("Browse trees in a random forest as Pythagorean previews."),
            "pythagorean-forest",
            _inputs("Random Forest"),
            _outputs("Tree"),
        ),
        WidgetDefinition(
            "pythagorean-tree",
            "visualize",
            i18n.t("Pythagorean Tree"),
            True,
            PythagoreanTreeScreen,
            i18n.t("Pythagorean tree visualization for decision trees."),
            "pythagorean-tree",
            _inputs("Tree"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "cn2-rule-viewer",
            "visualize",
            i18n.t("CN2 Rule Viewer"),
            True,
            CN2RuleViewerScreen,
            i18n.t("Review induced CN2 rules and inspect rows covered by the selected rules."),
            "cn2-rule-viewer",
            _inputs("Data", "Classifier"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "nomogram",
            "visualize",
            i18n.t("Nomogram"),
            True,
            NomogramScreen,
            i18n.t("Orange-style nomogram for logistic-regression feature contributions."),
            "nomogram",
            _inputs("Classifier", "Data"),
            _outputs("Features"),
        ),
        WidgetDefinition(
            "scoring-sheet-viewer",
            "visualize",
            i18n.t("Scoring Sheet Viewer"),
            True,
            ScoringSheetViewerScreen,
            i18n.t("Visualize the scoring-sheet model."),
            "scoring-sheet-viewer",
            _inputs("Classifier", "Data"),
            _outputs("Features"),
        ),
        WidgetDefinition(
            "constant",
            "model",
            i18n.t("Constant"),
            True,
            ConstantScreen,
            i18n.t("Predict the most frequent class or mean value."),
            "Constant",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "naive-bayes",
            "model",
            i18n.t("Naive Bayes"),
            True,
            NaiveBayesScreen,
            i18n.t("Gaussian Naive Bayes classifier."),
            "NaiveBayes",
            _inputs("Data"),
            _outputs("Classifier"),
        ),
        WidgetDefinition(
            "knn",
            "model",
            i18n.t("kNN"),
            True,
            KNNScreen,
            i18n.t("k-Nearest Neighbours classifier or regressor."),
            "KNN",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "tree",
            "model",
            i18n.t("Tree"),
            True,
            TreeScreen,
            i18n.t("Decision Tree with forward pruning."),
            "Tree",
            _inputs("Data"),
            _outputs("Tree"),
        ),
        WidgetDefinition(
            "random-forest",
            "model",
            i18n.t("Random Forest"),
            True,
            RandomForestScreen,
            i18n.t("Ensemble of decision trees."),
            "RandomForest",
            _inputs("Data"),
            _outputs("Random Forest"),
        ),
        WidgetDefinition(
            "logistic-regression",
            "model",
            i18n.t("Logistic Regression"),
            True,
            LogisticRegressionScreen,
            i18n.t("Logistic regression with L1/L2/no regularization."),
            "LogisticRegression",
            _inputs("Data"),
            _outputs("Classifier"),
        ),
        WidgetDefinition(
            "linear-regression",
            "model",
            i18n.t("Linear Regression"),
            True,
            LinearRegressionScreen,
            i18n.t("Linear regression with optional L1/L2/Elastic regularization."),
            "LinearRegression",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "svm",
            "model",
            i18n.t("SVM"),
            True,
            SVMScreen,
            i18n.t("Support Vector Machine with kernel selection."),
            "SVM",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "neural-network",
            "model",
            i18n.t("Neural Network"),
            True,
            NeuralNetworkScreen,
            i18n.t("Multi-layer perceptron with backpropagation."),
            "NN",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "adaboost",
            "model",
            i18n.t("AdaBoost"),
            True,
            AdaBoostScreen,
            i18n.t("AdaBoost ensemble with adaptive boosting."),
            "AdaBoost",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "gradient-boosting",
            "model",
            i18n.t("Gradient Boosting"),
            True,
            GradientBoostingScreen,
            i18n.t("Gradient Boosting on decision trees."),
            "GradientBoosting",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "sgd",
            "model",
            i18n.t("Stochastic Gradient Descent"),
            True,
            SGDScreen,
            i18n.t("SGD-based linear classifier or regressor."),
            "SGD",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "pls",
            "model",
            i18n.t("PLS"),
            True,
            PLSScreen,
            i18n.t("Partial Least Squares Regression."),
            "PLS",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "curve-fit",
            "model",
            i18n.t("Curve Fit"),
            True,
            CurveFitScreen,
            i18n.t("Fit a user-defined expression to numeric data."),
            "CurveFit",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "scoring-sheet",
            "model",
            i18n.t("Scoring Sheet"),
            True,
            ScoringSheetScreen,
            i18n.t("Fast explainable point-based classifier."),
            "ScoringSheet",
            _inputs("Data"),
            _outputs("Classifier"),
        ),
        WidgetDefinition(
            "cn2-rule-induction",
            "model",
            i18n.t("CN2 Rule Induction"),
            True,
            CN2RuleInductionScreen,
            i18n.t("Induce classification rules using CN2."),
            "CN2RuleInduction",
            _inputs("Data"),
            _outputs("Classifier"),
        ),
        WidgetDefinition(
            "calibrated-learner",
            "model",
            i18n.t("Calibrated Learner"),
            True,
            CalibratedLearnerScreen,
            i18n.t("Wrap a classifier with probability calibration."),
            "CalibratedLearner",
            _inputs("Data", "Classifier"),
            _outputs("Classifier"),
        ),
        WidgetDefinition(
            "stacking",
            "model",
            i18n.t("Stacking"),
            True,
            StackingScreen,
            i18n.t("Stack multiple models via a meta-learner."),
            "Stacking",
            _inputs("Data", "Model", "Aggregate"),
            _outputs("Model"),
            input_channels=("Data", "Model", "Aggregate"),
            multi_input_channels=("Model",),
            #semi_circular_inputs=True,
        ),
        WidgetDefinition(
            "save-model",
            "model",
            i18n.t("Save Model"),
            True,
            SaveModelScreen,
            i18n.t("Save a trained model to a file."),
            "SaveModel",
            _inputs("Model"),
            (),
        ),
        WidgetDefinition(
            "load-model",
            "model",
            i18n.t("Load Model"),
            True,
            LoadModelScreen,
            i18n.t("Load a trained model from a file."),
            "LoadModel",
            (),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "test-score",
            "evaluate",
            i18n.t("Test & Score"),
            True,
            TestAndScoreScreen,
            i18n.t("Evaluate models with cross-validation."),
            "TestAndScore",
            _inputs("Data", "Learner"),
            (),
            input_channels=("Data", "Learner"),
            multi_input_channels=("Learner",),
        ),
        WidgetDefinition(
            "confusion-matrix",
            "evaluate",
            i18n.t("Confusion Matrix"),
            True,
            ConfusionMatrixScreen,
            i18n.t("Show a confusion matrix for classifier predictions."),
            "score",
            _inputs("Data", "Model"),
            (),
        ),
        WidgetDefinition(
            "pca",
            "unsupervised",
            i18n.t("PCA"),
            True,
            OWPCA,
            i18n.t("Reduce dimensionality."),
            "pca",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Data",),
            input_channels=("Data",),
        ),
        WidgetDefinition(
            "hierarchical-clustering",
            "unsupervised",
            i18n.t("Hierarchical Clustering"),
            True,
            OWHierarchicalClustering,
            i18n.t("Build an agglomerative dendrogram from a distance matrix."),
            "HierarchicalClustering",
            _inputs("Distances", "Data Subset"),
            _outputs("Data"),
            output_channels=("Selected Data", "Other Data"),
        ),
        WidgetDefinition(
            "kmeans",
            "unsupervised",
            i18n.t("k-Means"),
            True,
            OWKMeans,
            i18n.t("Cluster numeric data with centroid-based Voronoi partitions."),
            "scatter",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Data",),
            input_channels=("Data",),
        ),
        WidgetDefinition(
            "dbscan",
            "unsupervised",
            i18n.t("DBSCAN"),
            True,
            DBSCANScreen,
            i18n.t("Group data with density-based clustering and inspect k-distance behaviour."),
            "dbscan",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "unsupervised-knn",
            "unsupervised",
            i18n.t("kNN"),
            True,
            KNNScreen,
            i18n.t("k-nearest neighbours model with the existing stable learner screen."),
            "KNN",
            _inputs("Data"),
            _outputs("Model"),
            output_channels=("Model",),
            input_channels=("Data",),
        ),
        WidgetDefinition(
            "distances",
            "unsupervised",
            i18n.t("Distances"),
            True,
            DistancesScreen,
            i18n.t("Compute a distance matrix from the current data."),
            "DistancesIcon",
            _inputs("Data"),
            _outputs("Distances"),
        ),
        WidgetDefinition(
            "distance-file",
            "unsupervised",
            i18n.t("Distance File"),
            True,
            DistanceFileScreen,
            i18n.t("Load a distance matrix from disk."),
            "distancefile",
            (),
            _outputs("Distances"),
        ),
        WidgetDefinition(
            "distance-matrix",
            "unsupervised",
            i18n.t("Distance Matrix"),
            True,
            DistanceMatrixScreen,
            i18n.t("Inspect and forward a distance matrix."),
            "DistanceMatrix",
            _inputs("Distances"),
            _outputs("Distances"),
        ),
        WidgetDefinition(
            "distance-transformation",
            "unsupervised",
            i18n.t("Distance Transformation"),
            True,
            DistanceTransformationScreen,
            i18n.t("Normalize or invert a distance matrix."),
            "distancetransformation",
            _inputs("Distances"),
            _outputs("Distances"),
        ),
        WidgetDefinition(
            "save-distance-matrix",
            "unsupervised",
            i18n.t("Save Distance Matrix"),
            True,
            SaveDistanceMatrixScreen,
            i18n.t("Save the incoming distance matrix to disk."),
            "SaveDistanceMatrix",
            _inputs("Distances"),
            (),
        ),
        WidgetDefinition(
            "correlations",
            "unsupervised",
            i18n.t("Correlations"),
            True,
            CorrelationsScreen,
            i18n.t("Review Pearson or Spearman correlations between numeric features."),
            "Correlations",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "distance-map",
            "unsupervised",
            i18n.t("Distance Map"),
            True,
            DistanceMapScreen,
            i18n.t("Visualize a distance matrix as a heat map."),
            "DistanceMap",
            _inputs("Distances"),
            (),
        ),
        WidgetDefinition(
            "correspondence-analysis",
            "unsupervised",
            i18n.t("Correspondence Analysis"),
            True,
            CAScreen,
            i18n.t("Project categorical values into correspondence-analysis coordinates."),
            "ca",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "mds",
            "unsupervised",
            i18n.t("MDS"),
            True,
            MDSScreen,
            i18n.t("Project instances into two dimensions using multidimensional scaling."),
            "mds",
            _inputs("Data", "Data Subset", "Distances"),
            _outputs("Data"),
            output_channels=("Selected Data", "Data"),
            input_channels=("Data", "Data Subset", "Distances"),
        ),
        WidgetDefinition(
            "outliers",
            "unsupervised",
            i18n.t("Outliers"),
            True,
            OutliersScreen,
            i18n.t("Detect inliers and outliers in numeric data."),
            "outliers",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Outliers", "Inliers", "Data"),
        ),
        WidgetDefinition(
            "tsne",
            "unsupervised",
            i18n.t("t-SNE"),
            True,
            TSNEScreen,
            i18n.t("Non-linear 2D/3D embedding via t-SNE."),
            "tsne",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "manifold-learning",
            "unsupervised",
            i18n.t("Manifold Learning"),
            True,
            ManifoldLearningScreen,
            i18n.t("Non-linear dimensionality reduction (Isomap, LLE, MDS…)."),
            "manifold",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "som",
            "unsupervised",
            i18n.t("SOM"),
            True,
            SOMScreen,
            i18n.t("Self-Organizing Map (Kohonen Map)."),
            "som",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "louvain-clustering",
            "unsupervised",
            i18n.t("Louvain Clustering"),
            True,
            LouvainClusteringScreen,
            i18n.t("Graph-based community detection via Louvain algorithm."),
            "louvain",
            _inputs("Data"),
            _outputs("Data"),
        ),
    ]
