from __future__ import annotations

from portakal_app.models import CategoryDefinition, PortDefinition, WidgetDefinition
from portakal_app.ui import i18n
from portakal_app.ui.screens.color_screen import ColorScreen
from portakal_app.ui.screens.column_statistics_screen import ColumnStatisticsScreen
from portakal_app.ui.screens.csv_import_screen import CSVImportScreen
from portakal_app.ui.screens.data_info_screen import DataInfoScreen
from portakal_app.ui.screens.data_table_screen import DataTableScreen
from portakal_app.ui.screens.datasets_screen import DatasetsScreen
from portakal_app.ui.screens.edit_domain_screen import EditDomainScreen
from portakal_app.ui.screens.file_screen import FileScreen
from portakal_app.ui.screens.paint_data_screen import PaintDataScreen
from portakal_app.ui.screens.placeholder_screen import PlaceholderScreen
from portakal_app.ui.screens.rank_screen import RankScreen
from portakal_app.ui.screens.save_data_screen import SaveDataScreen

from portakal_app.ui.screens.aggregate_columns_screen import AggregateColumnsScreen
from portakal_app.ui.screens.apply_domain_screen import ApplyDomainScreen
from portakal_app.ui.screens.continuize_screen import ContinuizeScreen
from portakal_app.ui.screens.data_sampler_screen import DataSamplerScreen
from portakal_app.ui.screens.discretize_screen import DiscretizeScreen
from portakal_app.ui.screens.melt_screen import MeltScreen
from portakal_app.ui.screens.purge_domain_screen import PurgeDomainScreen
from portakal_app.ui.screens.randomize_screen import RandomizeScreen
from portakal_app.ui.screens.select_by_index_screen import SelectByIndexScreen
from portakal_app.ui.screens.split_screen import SplitScreen
from portakal_app.ui.screens.transpose_screen import TransposeScreen
from portakal_app.ui.screens.unique_screen import UniqueScreen

from portakal_app.ui.screens.concatenate_screen import ConcatenateScreen
from portakal_app.ui.screens.formula_screen import FormulaScreen
from portakal_app.ui.screens.create_class_screen import CreateClassScreen
from portakal_app.ui.screens.create_instance_screen import CreateInstanceScreen
from portakal_app.ui.screens.group_by_screen import GroupByScreen
from portakal_app.ui.screens.impute_screen import ImputeScreen
from portakal_app.ui.screens.merge_data_screen import MergeDataScreen
from portakal_app.ui.screens.pivot_table_screen import PivotTableScreen
from portakal_app.ui.screens.preprocess_screen import PreprocessScreen
from portakal_app.ui.screens.python_script_screen import PythonScriptScreen
from portakal_app.ui.screens.select_columns_screen import SelectColumnsScreen
from portakal_app.ui.screens.select_rows_screen import SelectRowsScreen

from portakal_app.ui.screens.bar_plot_screen import BarPlotScreen
from portakal_app.ui.screens.box_plot_screen import BoxPlotScreen
from portakal_app.ui.screens.distributions_screen import DistributionsScreen
from portakal_app.ui.screens.sieve_diagram_screen import SieveDiagramScreen
from portakal_app.ui.screens.mosaic_display_screen import MosaicDisplayScreen
from portakal_app.ui.screens.freeviz_screen import FreeVizScreen
from portakal_app.ui.screens.linear_projection_screen import LinearProjectionScreen
from portakal_app.ui.screens.radviz_screen import RadvizScreen
from portakal_app.ui.screens.heat_map_screen import HeatMapScreen
from portakal_app.ui.screens.line_plot_screen import LinePlotScreen
from portakal_app.ui.screens.scatter_plot_screen import ScatterPlotScreen
from portakal_app.ui.screens.tree_viewer_screen import TreeViewerScreen
from portakal_app.ui.screens.violin_plot_screen import ViolinPlotScreen
from portakal_app.ui.screens.venn_diagram_screen import VennDiagramScreen
from portakal_app.ui.screens.silhouette_plot_screen import SilhouettePlotScreen
from portakal_app.ui.screens.pythagorean_forest_screen import PythagoreanForestScreen
from portakal_app.ui.screens.pythagorean_tree_screen import PythagoreanTreeScreen
from portakal_app.ui.screens.cn2_rule_viewer_screen import CN2RuleViewerScreen
from portakal_app.ui.screens.nomogram_screen import NomogramScreen
from portakal_app.ui.screens.scoring_sheet_viewer_screen import ScoringSheetViewerScreen


def _placeholder_factory(title: str, description: str):
    def factory() -> PlaceholderScreen:
        return PlaceholderScreen(title=i18n.t(title), message=i18n.t(description))

    return factory


def _inputs(*labels: str) -> tuple[PortDefinition, ...]:
    return tuple(PortDefinition(id=f"in-{index}", label=label) for index, label in enumerate(labels, start=1))


def _outputs(*labels: str) -> tuple[PortDefinition, ...]:
    return tuple(PortDefinition(id=f"out-{index}", label=label) for index, label in enumerate(labels, start=1))


def build_categories() -> list[CategoryDefinition]:
    return [
        CategoryDefinition(id="data", label=i18n.t("Data")),
        CategoryDefinition(id="transform", label=i18n.t("Transform")),
        CategoryDefinition(id="visualize", label=i18n.t("Visualize")),
        CategoryDefinition(id="model", label=i18n.t("Model")),
        CategoryDefinition(id="evaluate", label=i18n.t("Evaluate")),
        CategoryDefinition(id="unsupervised", label=i18n.t("Unsupervised")),
    ]


def build_widgets() -> list[WidgetDefinition]:
    return [
        WidgetDefinition(
            "file",
            "data",
            i18n.t("File"),
            True,
            FileScreen,
            i18n.t("Load a file dataset."),
            "file",
            (),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "csv-import",
            "data",
            i18n.t("CSV File Import"),
            True,
            CSVImportScreen,
            i18n.t("Preset-based import flow."),
            "csv",
            (),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "datasets",
            "data",
            i18n.t("Datasets"),
            True,
            DatasetsScreen,
            i18n.t("Explore packaged datasets."),
            "dataset",
            (),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "data-table",
            "data",
            i18n.t("Data Table"),
            True,
            DataTableScreen,
            i18n.t("Inspect loaded rows."),
            "table",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "paint-data",
            "data",
            i18n.t("Paint Data"),
            True,
            PaintDataScreen,
            i18n.t("Edit data manually."),
            "paint",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "data-info",
            "data",
            i18n.t("Data Info"),
            True,
            DataInfoScreen,
            i18n.t("Profile the dataset."),
            "info",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "rank",
            "data",
            i18n.t("Rank"),
            True,
            RankScreen,
            i18n.t("Rank features."),
            "rank",
            _inputs("Data"),
            _outputs("Scores"),
        ),
        WidgetDefinition(
            "edit-domain",
            "data",
            i18n.t("Edit Domain"),
            True,
            EditDomainScreen,
            i18n.t("Manage column roles."),
            "edit",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "color",
            "data",
            i18n.t("Color"),
            True,
            ColorScreen,
            i18n.t("Assign color metadata."),
            "color",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "column-statistics",
            "data",
            i18n.t("Column Statistics"),
            True,
            ColumnStatisticsScreen,
            i18n.t("Deep dive into column distributions."),
            "stats",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "save-data",
            "data",
            i18n.t("Save Data"),
            True,
            SaveDataScreen,
            i18n.t("Export the current dataset."),
            "save",
            _inputs("Data"),
            (),
        ),
        # --- Transform: Active widgets ---
        WidgetDefinition(
            "select-by-index",
            "transform",
            i18n.t("Select by Data Index"),
            True,
            SelectByIndexScreen,
            i18n.t("Match rows by index subset."),
            "index",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Matching Data", "Non-matching Data"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "randomize",
            "transform",
            i18n.t("Randomize"),
            True,
            RandomizeScreen,
            i18n.t("Shuffle rows or columns."),
            "randomize",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "purge-domain",
            "transform",
            i18n.t("Purge Domain"),
            True,
            PurgeDomainScreen,
            i18n.t("Remove unused values and constant features."),
            "purge",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "unique",
            "transform",
            i18n.t("Unique"),
            True,
            UniqueScreen,
            i18n.t("Filter duplicate rows."),
            "unique",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "apply-domain",
            "transform",
            i18n.t("Apply Domain"),
            True,
            ApplyDomainScreen,
            i18n.t("Apply template domain structure."),
            "domain",
            _inputs("Data"),
            _outputs("Data"),
            input_channels=("Data", "Template Data"),
        ),
        # --- Transform: Placeholder widgets (to be implemented) ---
        WidgetDefinition(
            "data-sampler",
            "transform",
            i18n.t("Data Sampler"),
            True,
            DataSamplerScreen,
            i18n.t("Sample a subset of the data."),
            "sampler",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Data Sample", "Remaining Data"),
        ),
        WidgetDefinition(
            "select-columns",
            "transform",
            i18n.t("Select Columns"),
            True,
            SelectColumnsScreen,
            i18n.t("Choose feature sets."),
            "columns",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "select-rows",
            "transform",
            i18n.t("Select Rows"),
            True,
            SelectRowsScreen,
            i18n.t("Filter rows by conditions."),
            "rows",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Matching Data", "Unmatched Data"),
        ),
        WidgetDefinition(
            "transpose",
            "transform",
            i18n.t("Transpose"),
            True,
            TransposeScreen,
            i18n.t("Flip rows and columns."),
            "transpose",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "split",
            "transform",
            i18n.t("Split"),
            True,
            SplitScreen,
            i18n.t("Split string column into indicators."),
            "split",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "merge-data",
            "transform",
            i18n.t("Merge Data"),
            True,
            MergeDataScreen,
            i18n.t("Join two datasets by column values."),
            "merge",
            _inputs("Data", "Extra Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "concatenate",
            "transform",
            i18n.t("Concatenate"),
            True,
            ConcatenateScreen,
            i18n.t("Append datasets vertically."),
            "concatenate",
            _inputs("Data"),
            _outputs("Data"),
            input_channels=("Primary Data", "Additional Data"),
            multi_input_channels=("Additional Data",),
        ),
        WidgetDefinition(
            "aggregate-columns",
            "transform",
            i18n.t("Aggregate Columns"),
            True,
            AggregateColumnsScreen,
            i18n.t("Compute row-wise aggregations."),
            "aggregate",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "group-by",
            "transform",
            i18n.t("Group By"),
            True,
            GroupByScreen,
            i18n.t("Group and aggregate data."),
            "groupby",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "pivot-table",
            "transform",
            i18n.t("Pivot Table"),
            True,
            PivotTableScreen,
            i18n.t("Create cross-tabulations."),
            "pivot",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "preprocess",
            "transform",
            "Preprocess",
            True,
            PreprocessScreen,
            i18n.t("Build preprocessing pipelines."),
            "preprocess",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "impute",
            "transform",
            i18n.t("Impute"),
            True,
            ImputeScreen,
            i18n.t("Fill missing values."),
            "impute",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "continuize",
            "transform",
            i18n.t("Continuize"),
            True,
            ContinuizeScreen,
            i18n.t("Convert categorical to numeric."),
            "continuize",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "discretize",
            "transform",
            i18n.t("Discretize"),
            True,
            DiscretizeScreen,
            i18n.t("Convert numeric to categorical."),
            "discretize",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "melt",
            "transform",
            i18n.t("Melt"),
            True,
            MeltScreen,
            i18n.t("Wide to long format."),
            "melt",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "create-class",
            "transform",
            i18n.t("Create Class"),
            True,
            CreateClassScreen,
            i18n.t("Create class from string patterns."),
            "createclass",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "create-instance",
            "transform",
            i18n.t("Create Instance"),
            True,
            CreateInstanceScreen,
            i18n.t("Create a single data instance."),
            "createinstance",
            _inputs("Data"),
            _outputs("Data"),
            input_channels=("Data", "Reference"),
        ),
        WidgetDefinition(
            "formula",
            "transform",
            i18n.t("Formula"),
            True,
            FormulaScreen,
            i18n.t("Construct features with expressions."),
            "formula",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "python-script",
            "transform",
            i18n.t("Python Script"),
            True,
            PythonScriptScreen,
            i18n.t("Run custom Python code."),
            "python",
            _inputs("Data"),
            _outputs("Data"),
        ),
        WidgetDefinition(
            "tree-viewer",
            "visualize",
            i18n.t("Tree Viewer"),
            True,
            TreeViewerScreen,
            i18n.t("Inspect trained tree structures and node selections."),
            "model",
            _inputs("Tree"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "box-plot",
            "visualize",
            i18n.t("Box Plot"),
            True,
            BoxPlotScreen,
            i18n.t("Visualize numeric quartiles or discrete value frequencies."),
            "stats",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "violin-plot",
            "visualize",
            i18n.t("Violin Plot"),
            True,
            ViolinPlotScreen,
            i18n.t("Show smoothed numeric distributions with selectable ranges."),
            "stats",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "distributions",
            "visualize",
            i18n.t("Distributions"),
            True,
            DistributionsScreen,
            i18n.t("Explore histograms and categorical distributions."),
            "barplot",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "scatter-plot",
            "visualize",
            i18n.t("Scatter Plot"),
            True,
            ScatterPlotScreen,
            i18n.t("Explore points visually."),
            "scatter",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data", "Features"),
            input_channels=("Data", "Data Subset", "Features"),
        ),
        WidgetDefinition(
            "line-plot",
            "visualize",
            i18n.t("Line Plot"),
            True,
            LinePlotScreen,
            i18n.t("Compare instance profiles across numeric features."),
            "linearprojection",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "bar-plot",
            "visualize",
            i18n.t("Bar Plot"),
            True,
            BarPlotScreen,
            i18n.t("Frequency bars for categorical or binned numeric columns."),
            "barplot",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "sieve-diagram",
            "visualize",
            i18n.t("Sieve Diagram"),
            True,
            SieveDiagramScreen,
            i18n.t("Association between two categorical variables."),
            "sieve",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data", "Features"),
        ),
        WidgetDefinition(
            "mosaic-display",
            "visualize",
            i18n.t("Mosaic Display"),
            True,
            MosaicDisplayScreen,
            i18n.t("Proportional mosaic plot for two categorical variables."),
            "mosaic",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "freeviz",
            "visualize",
            i18n.t("FreeViz"),
            True,
            FreeVizScreen,
            i18n.t("Force-directed linear projection onto 2D."),
            "freeviz",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data", "Components"),
            input_channels=("Data", "Data Subset"),
        ),
        WidgetDefinition(
            "linear-projection",
            "visualize",
            i18n.t("Linear Projection"),
            True,
            LinearProjectionScreen,
            i18n.t("Scatter plot of two user-selected numeric axes."),
            "linearprojection",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data", "Components"),
            input_channels=("Data", "Data Subset", "Projection"),
        ),
        WidgetDefinition(
            "radviz",
            "visualize",
            i18n.t("Radviz"),
            True,
            RadvizScreen,
            i18n.t("Radial visualization with feature anchors on a circle."),
            "radviz",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "heat-map",
            "visualize",
            i18n.t("Heat Map"),
            True,
            HeatMapScreen,
            i18n.t("Pearson correlation matrix for numeric columns."),
            "heatmap",
            _inputs("Data"),
            (),
        ),
        WidgetDefinition(
            "venn-diagram",
            "visualize",
            i18n.t("Venn Diagram"),
            True,
            VennDiagramScreen,
            i18n.t("Overlap of rows or features across multiple datasets."),
            "venn",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
            input_channels=("Data 1", "Data 2", "Data 3", "Data 4", "Data 5"),
        ),
        WidgetDefinition(
            "silhouette-plot",
            "visualize",
            i18n.t("Silhouette Plot"),
            True,
            SilhouettePlotScreen,
            i18n.t("Assess cluster quality with silhouette scores."),
            "silhouette",
            _inputs("Data"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "pythagorean-forest",
            "visualize",
            i18n.t("Pythagorean Forest"),
            True,
            PythagoreanForestScreen,
            i18n.t("Browse trees in a random forest as Pythagorean previews."),
            "pythagorean-forest",
            _inputs("Random Forest"),
            _outputs("Tree"),
        ),
        WidgetDefinition(
            "pythagorean-tree",
            "visualize",
            i18n.t("Pythagorean Tree"),
            True,
            PythagoreanTreeScreen,
            i18n.t("Pythagorean tree visualization for decision trees."),
            "pythagorean-tree",
            _inputs("Tree"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "cn2-rule-viewer",
            "visualize",
            i18n.t("CN2 Rule Viewer"),
            True,
            CN2RuleViewerScreen,
            i18n.t("Review induced CN2 rules and inspect rows covered by the selected rules."),
            "cn2-rule-viewer",
            _inputs("Data", "Classifier"),
            _outputs("Data"),
            output_channels=("Selected Data", "Annotated Data"),
        ),
        WidgetDefinition(
            "nomogram",
            "visualize",
            i18n.t("Nomogram"),
            True,
            NomogramScreen,
            i18n.t("Orange-style nomogram for logistic-regression feature contributions."),
            "nomogram",
            _inputs("Classifier", "Data"),
            _outputs("Features"),
        ),
        WidgetDefinition(
            "scoring-sheet-viewer",
            "visualize",
            i18n.t("Scoring Sheet Viewer"),
            True,
            ScoringSheetViewerScreen,
            i18n.t("Visualize the scoring-sheet model."),
            "scoring-sheet-viewer",
            _inputs("Classifier", "Data"),
            _outputs("Features"),
        ),
        WidgetDefinition(
            "linear-regression",
            "model",
            i18n.t("Linear Regression"),
            False,
            _placeholder_factory("Linear Regression", "Model widgets will be integrated by a later group."),
            i18n.t("Train a baseline model."),
            "model",
            _inputs("Data"),
            _outputs("Model"),
        ),
        WidgetDefinition(
            "test-score",
            "evaluate",
            i18n.t("Test & Score"),
            False,
            _placeholder_factory("Test & Score", "Evaluation widgets will be integrated by a later group."),
            i18n.t("Measure model performance."),
            "score",
            _inputs("Data", "Model"),
            _outputs("Scores"),
        ),
        WidgetDefinition(
            "pca",
            "unsupervised",
            i18n.t("PCA"),
            False,
            _placeholder_factory("PCA", "Unsupervised widgets will be integrated by a later group."),
            i18n.t("Reduce dimensionality."),
            "pca",
            _inputs("Data"),
            _outputs("Data"),
        ),
    ]
